import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import { Menu } from "../components/menu";
import { Layout } from "../components/Layout";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to homepage</h1>
    </Layout>
  );
};

export default Home;
